### ISSUE TITLE
undefined reference to symbol 'XIQueryVersion'

### ISSUE THREAD

**Issue by kasbah** [Ryochan7/antimicro#198]
~~~
Linking CXX executable bin/antimicro
/usr/bin/ld: CMakeFiles/antimicro.dir/src/x11extras.cpp.o: undefined reference to symbol 'XIQueryVersion'
//usr/lib/i386-linux-gnu/libXi.so.6: error adding symbols: DSO missing from command line
~~~

Ubuntu 14.04 32-bit, libxi-dev 2:1.7.1.901-1ubuntu1

**Comment by Ryochan7** [comment]
Can you post the line shown on the command line when the actual linking is attempted? The only reason that I would think that compiling would fail is that -lXi is not present. I have tested compiling antimicro under Ubuntu 14.04 32 bit and it compiles successfully.

**Comment by xenomachina** [comment]
Funny, I just ran into this problem and found this issue via Google.

I'm trying to build on Ubuntu 14.04 as well, libxi-dev 1.7.1.901-1ubuntu1.1, but 64-bit.

Here's the command causing the error (wrapped to avoid weirdness):

        /usr/bin/c++
        -fPIE
        CMakeFiles/antimicro.dir/src/main.cpp.o
        CMakeFiles/antimicro.dir/src/mainwindow.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttonwidget.cpp.o
        CMakeFiles/antimicro.dir/src/joystick.cpp.o
        CMakeFiles/antimicro.dir/src/joybutton.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttontypes/joygradientbutton.cpp.o
        CMakeFiles/antimicro.dir/src/event.cpp.o
        CMakeFiles/antimicro.dir/src/inputdaemon.cpp.o
        CMakeFiles/antimicro.dir/src/joyaxis.cpp.o
        CMakeFiles/antimicro.dir/src/joyaxiswidget.cpp.o
        CMakeFiles/antimicro.dir/src/joydpad.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttontypes/joydpadbutton.cpp.o
        CMakeFiles/antimicro.dir/src/axiseditdialog.cpp.o
        CMakeFiles/antimicro.dir/src/xmlconfigreader.cpp.o
        CMakeFiles/antimicro.dir/src/xmlconfigwriter.cpp.o
        CMakeFiles/antimicro.dir/src/joytabwidget.cpp.o
        CMakeFiles/antimicro.dir/src/axisvaluebox.cpp.o
        CMakeFiles/antimicro.dir/src/advancebuttondialog.cpp.o
        CMakeFiles/antimicro.dir/src/simplekeygrabberbutton.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttonslot.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttontypes/joyaxisbutton.cpp.o
        CMakeFiles/antimicro.dir/src/aboutdialog.cpp.o
        CMakeFiles/antimicro.dir/src/setjoystick.cpp.o
        CMakeFiles/antimicro.dir/src/sdleventreader.cpp.o
        CMakeFiles/antimicro.dir/src/setaxisthrottledialog.cpp.o
        CMakeFiles/antimicro.dir/src/keyboard/virtualkeypushbutton.cpp.o
        CMakeFiles/antimicro.dir/src/keyboard/virtualkeyboardmousewidget.cpp.o
        CMakeFiles/antimicro.dir/src/keyboard/virtualmousepushbutton.cpp.o
        CMakeFiles/antimicro.dir/src/buttoneditdialog.cpp.o
        CMakeFiles/antimicro.dir/src/commandlineutility.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstick.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttontypes/joycontrolstickbutton.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttontypes/joycontrolstickmodifierbutton.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstickeditdialog.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstickpushbutton.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstickbuttonpushbutton.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstickstatusbox.cpp.o
        CMakeFiles/antimicro.dir/src/advancestickassignmentdialog.cpp.o
        CMakeFiles/antimicro.dir/src/dpadpushbutton.cpp.o
        CMakeFiles/antimicro.dir/src/dpadeditdialog.cpp.o
        CMakeFiles/antimicro.dir/src/vdpad.cpp.o
        CMakeFiles/antimicro.dir/src/joydpadbuttonwidget.cpp.o
        CMakeFiles/antimicro.dir/src/quicksetdialog.cpp.o
        CMakeFiles/antimicro.dir/src/mousehelper.cpp.o
        CMakeFiles/antimicro.dir/src/mousesettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/mousedialog/mousecontrolsticksettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/mousedialog/mouseaxissettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/mousedialog/mousebuttonsettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/mousedialog/mousedpadsettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/joytabwidgetcontainer.cpp.o
        CMakeFiles/antimicro.dir/src/mousedialog/springmoderegionpreview.cpp.o
        CMakeFiles/antimicro.dir/src/joystickstatuswindow.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttonstatusbox.cpp.o
        CMakeFiles/antimicro.dir/src/qtkeymapperbase.cpp.o
        CMakeFiles/antimicro.dir/src/flashbuttonwidget.cpp.o
        CMakeFiles/antimicro.dir/src/xmlconfigmigration.cpp.o
        CMakeFiles/antimicro.dir/src/qkeydisplaydialog.cpp.o
        CMakeFiles/antimicro.dir/src/antkeymapper.cpp.o
        CMakeFiles/antimicro.dir/src/inputdevice.cpp.o
        CMakeFiles/antimicro.dir/src/mainsettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontroller/gamecontrollertriggerbutton.cpp.o
        CMakeFiles/antimicro.dir/src/setnamesdialog.cpp.o
        CMakeFiles/antimicro.dir/src/autoprofileinfo.cpp.o
        CMakeFiles/antimicro.dir/src/addeditautoprofiledialog.cpp.o
        CMakeFiles/antimicro.dir/src/editalldefaultautoprofiledialog.cpp.o
        CMakeFiles/antimicro.dir/src/common.cpp.o
        CMakeFiles/antimicro.dir/src/localantimicroserver.cpp.o
        CMakeFiles/antimicro.dir/src/extraprofilesettingsdialog.cpp.o
        CMakeFiles/antimicro.dir/src/antimicrosettings.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttoncontextmenu.cpp.o
        CMakeFiles/antimicro.dir/src/joycontrolstickcontextmenu.cpp.o
        CMakeFiles/antimicro.dir/src/dpadcontextmenu.cpp.o
        CMakeFiles/antimicro.dir/src/joyaxiscontextmenu.cpp.o
        CMakeFiles/antimicro.dir/src/stickpushbuttongroup.cpp.o
        CMakeFiles/antimicro.dir/src/dpadpushbuttongroup.cpp.o
        CMakeFiles/antimicro.dir/src/joybuttonmousehelper.cpp.o
        CMakeFiles/antimicro.dir/src/logger.cpp.o
        CMakeFiles/antimicro.dir/src/inputdevicebitarraystatus.cpp.o
        CMakeFiles/antimicro.dir/src/applaunchhelper.cpp.o
        CMakeFiles/antimicro.dir/src/firstrunwizard/firstrunwizard.cpp.o
        CMakeFiles/antimicro.dir/src/firstrunwizard/mousesettingspage.cpp.o
        CMakeFiles/antimicro.dir/src/firstrunwizard/firstrunwelcomepage.cpp.o
        CMakeFiles/antimicro.dir/src/firstrunwizard/languageselectionpage.cpp.o
        CMakeFiles/antimicro.dir/src/eventhandlers/baseeventhandler.cpp.o
        CMakeFiles/antimicro.dir/src/eventhandlerfactory.cpp.o
        CMakeFiles/antimicro.dir/src/x11extras.cpp.o
        CMakeFiles/antimicro.dir/src/qtx11keymapper.cpp.o
        CMakeFiles/antimicro.dir/src/unixcapturewindowutility.cpp.o
        CMakeFiles/antimicro.dir/src/autoprofilewatcher.cpp.o
        CMakeFiles/antimicro.dir/src/capturedwindowinfodialog.cpp.o
        CMakeFiles/antimicro.dir/src/eventhandlers/xtesteventhandler.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontroller/gamecontroller.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontroller/gamecontrollerdpad.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontroller/gamecontrollerset.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontroller/gamecontrollertrigger.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontrollermappingdialog.cpp.o
        CMakeFiles/antimicro.dir/src/gamecontrollerexample.cpp.o
        CMakeFiles/antimicro.dir/qrc_resources.cpp.o
        CMakeFiles/antimicro.dir/antimicro_automoc.cpp.o
        -o bin/antimicro
        -rdynamic
        /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.2.1
        /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.2.1
        /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.2.1
        /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.2.1
        -lX11
        -lXtst
        -lSDL2
        /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.2.1

I don't see -lXi anywhere in that. I don't know cmake, so I don't know the right way to fix this.

**Comment by Ryochan7** [comment]
Thank you xenomachina. The proper library was not being linked due to a change that I made a few days ago in commit 17573f832ee59a4fbb175d3946ce89d3649077d4. The XIQueryVersion function was only being used previously when the program was compiled with uinput support. Now, it is used in the X11Extras class but the CMakeLists.txt file was not updated to account for the change. My tests builds compiled support for uinput so it didn't fit this situation. The most recent commit should fix the problem.

**Comment by xenomachina** [comment]
Thanks! Pulling the most recent commit fixed the problem for me.
