### ISSUE TITLE
unable to compile on armhf Debian Wheezy

### ISSUE THREAD

**Issue by eadmaster** [Ryochan7/antimicro#188]
$ gcc --version
    gcc (Debian 4.6.3-14+rpi1) 4.6.3
    $ cd antimicro; mkdir build && cd build
    $ cmake .. -DUSE_SDL_2=OFF
... (everything seems fine)
    $ make
    /home/pi/antimicro-2.13/src/inputdaemon.cpp: In member function ‘void         InputDaemon::modifyUnplugEvents(QQueue<SDL_Event>*)’:
    /home/pi/antimicro-2.13/src/inputdaemon.cpp:586:66: error: ‘class InputDevice’ has no member named ‘getSDLJoystickID’
    make[2]: *** [CMakeFiles/antimicro.dir/src/inputdaemon.cpp.o] Error 1
    make[1]: *** [CMakeFiles/antimicro.dir/all] Error 2
    make: *** [all] Error 2

**Comment by Ryochan7** [comment]
It looks like code that was dependent on SDL 2 hotplugging support was being included and that caused the problem. I have wrapped the appropriate code and antimicro compiles when building with SDL 1.2 support again. At this point, SDL 1.2 support in antimicro is considered deprecated so I haven't really tested whether the code compiles with SDL 1.2 in some time. Thank you for pointing out the problem in the code.
